export const enum TokenKind {
	Fn = "fn",
	EOF = "EOF",
	Mut = "let",
	Dot = "dot",
	Final = "final",
	Comma = "comma",
	Colon = "colon",
	Return = "return",
	Number = "number",
	String = "string",
	OpenBrace = "'{'",
	OpenParan = "'('",
	CloseBrace = "'}'",
	CloseParan = "')'",
	Identifier = "identifier",
	OpenBracket = "'['",
	CloseBracket = "']'",
	BinaryOpreator = "binary opreator (+,-,*,/)",
	AssignmentOpreator = "=",
}
